# Generated by Django 4.2.2 on 2023-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('group', models.CharField(choices=[('DEVELOPER', 'developer'), ('MARKETER', 'marketer')], max_length=32)),
            ],
        ),
    ]
