# Generated by Django 4.2.2 on 2023-06-25 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('output', models.TextField()),
                ('query_date', models.DateTimeField(default=datetime.datetime(2023, 6, 26, 1, 25, 43, 41852))),
                ('feedback', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], max_length=8)),
            ],
        ),
    ]
